export default {
  PLATE: require('../assets/images/plate.png'),
  DISCOVER: require('../assets/images/discover.png'),
  DELIVER: require('../assets/images/deliver.png'),
  FAVORITE: require('../assets/images/favorite.png'),
  FACEBOOK: require('../assets/images/facebook.png'),
  GOOGLE: require('../assets/images/google.png'),
  LOADING: require('../assets/images/loading.json'),
  DELIVERY_TIME: require('../assets/images/delivery_time.png'),
  DELIVERY_CHARGE: require('../assets/images/delivery_charge.png'),
  MARKER: require('../assets/images/marker.png'),
  EMPTY_CART: require('../assets/images/empty_cart.png'),
  COMPLETE: require('../assets/images/complete.png'),
  HISTORY_ORDER: require('../assets/images/history_order.png'),
  RATING: require('../assets/images/rating.png'),
  USER_NOT_FOUND: require('../assets/images/user-not-found.png'),
  BANNED: require('../assets/images/banned.png'),
};
